services:
  db:
    image: postgres:16-alpine
    container_name: self_studio_db
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: self_studio_warehouse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
